language: c
sudo: false
addons:
    apt:
        sources:
            - r-packages-precise
        packages:
            - r-base-dev
            - r-recommended
            - haskell-platform
            - lmodern
            - pdftk
before_install:
- export R_LIBS_USER=$HOME/prebuild/R PATH=$PATH:$HOME/prebuild/gpp/bin:$HOME/prebuild/texlive/bin/x86_64-linux:$HOME/prebuild/haskell/bin PYTHONUSERBASE=$HOME/prebuild/python
- ./.travis.git
- ./.travis.deps
script:
- (make && make) &> /dev/null
- make |& tee error.log
- "! grep -q 'LaTeX Error' error.log"
after_success:
- mkdir -p kuleuven-templates
- for i in *.pdf; do
    pdftk "$i" output "$i.tmp" uncompress;
    sed -i '/^\/\(Mod\|Creation\)Date (D:/s/[0-9]/0/g' "$i.tmp";
    pdftk "$i.tmp" output "$i" compress;
    sed -i '/^\/ID \[/s/[0-9a-fA-F]/D/g' "$i";
    rm "$i.tmp";
  done
- mv *.pdf kuleuven-templates/
- git add -f kuleuven-templates/
- git commit -m "$(git log --format=%B -n 1 $TRAVIS_COMMIT)"
- if test "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master"; then
    git push deploy deploy:master;
  fi
